library(tidyverse)
gapfinder(1).__C__sourceEnvironment)
nrow(gapminder)
nrow(gapminder.csv)
Gapminder<-read_csv("gapminder.csv")
summary(Gapminder)
unique(Gapminder$country)
select(Gapminder,country,year)
select(Gapminder,-pop)
select(Gapminder, 1:3)
select(Gapminder,contains ("e"))
select(Gapminder,starts_with("co"))
select(Gapminder,ends_with("p"))
rename(Gapminder,population =pop)
select(Gapminder, population =pop)
rename(Gapfinder, lifeexp_gdpercap)
Filter(gapminder,continent==Europe)

